version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    environment:
      ## build.properties
      - sf.username: iamnicwu@163.com
      - sf.password: Abc123456qVSjFrNMHmitpwqxlT3AbK7B
      - sf.serverurl: https://login.salesforce.com
      - sf.maxPoll: 600
      ## settings to change in branch properties
      ## copy the build.master.properties to build.[branch].properties
      - sf.runallTests: true
      - sf.checkOnly: true
      - build.cmd: RunLocalTests
      - DEPLOYDIR: force-app\main\default\classes
    steps:
      - checkout
      - run:
          name: "create sfdx folder"
          command: |
            mkdir sfdx
      - run:
          name: "Download and Unzip Ant"
          command: |
            wget "https://gs0.salesforce.com/dwnld/SfdcAnt/salesforce_ant_47.0.zip"; unzip salesforce_ant_47.0.zip -d sfdx
      - run:
          name: "DeployCodeCheckOnly"
          command: |
            cd ./sfdx/; ant deployCodeCheckOnly
